resolver: ghc-8.0.2

packages:
- '.'
- location:
    git: https://github.com/haskell-distributed/distributed-process-client-server.git
    commit: 22fa1dc33b73a10fb82e949dd5323f147f2017ec
  extra-dep: true
- location:
    git: https://github.com/haskell-distributed/distributed-process-supervisor.git
    commit: bf2b5b06ed400ecc5906d4ef9a0c172810488435
  extra-dep: true

extra-deps:
- distributed-process-0.6.6         # missing snapshot
- distributed-process-extras-0.3.1  # missing snapshot
- distributed-process-async-0.2.4   # missing snapshot
- distributed-process-systest-0.1.1 # missing prior to Jan-2017
- rematch-0.2.0.0
- data-accessor-0.2.2.7
- distributed-static-0.3.8
- fingertree-0.1.4.1
- hashable-1.2.7.0
- mtl-2.2.2
- network-transport-0.4.4.0
- random-1.1
- rank1dynamic-0.3.3.0
- stm-2.4.5.0
- syb-0.6
- unordered-containers-0.2.9.0
- text-1.2.3.0
- transformers-compat-0.6.1.6
- transformers-0.5.5.0
- exceptions-0.8.3

- lens-4.16.1
- base-orphans-0.7
- bifunctors-5.5.2
- cabal-doctest-1.0.6
- call-stack-0.1.0
- comonad-5.0.3
- contravariant-1.4.1
- distributive-0.5.3
- free-5.0.1
- kan-extensions-5.1
- parallel-3.2.1.1
- profunctors-5.2.2
- reflection-2.1.3
- semigroupoids-5.2.2
- semigroups-0.18.4
- tagged-0.8.5
- th-abstraction-0.2.6.0
- vector-0.12.0.1
- void-0.7.2
- StateVar-1.1.0.4
- adjunctions-4.4
- fail-4.9.0.0
- primitive-0.6.3.0
- transformers-base-0.4.5.2
- network-transport-tcp-0.4.2
- network-2.6.3.5
